name: project_aegis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.2.0
  - matplotlib>=3.7.0
  - pip
  - pip:
    - adversarial-robustness-toolbox>=1.15.0
    - kaggle>=1.5.16
